### ISSUE TITLE
Copyright notices

### ISSUE THREAD

**Issue by arnaud-lb** [php-kafka/php-simple-kafka-client#24]
Although the license permits copy and redistribution in quite free terms, it's not ethical to strip the copyright notice from all the source files, or to remove the git history from a fork.

Also, creating a projet/organization with such a generic name, when other projects exist, is a bit unfair.

**Comment by nick-zh** [comment]
I removed it, because it seems that these were outdated, the project seems to be under MIT and the source files were still under a php licence, i checked other extensions as well and found it to be a mix, but i prefer the approach to "maintain" the licence only in one place. It was not my intention to hide anything, as you can see, i prominently state that this project is based on the original extension.

I removed the history of this fork, to avoid people using old tags with e.g. php5 support etc. that this project is not supporting.
Regarding the naming, it was fitting, so i started this to gather things related to kafka that i want to give back to the community.

**Comment by nick-zh** [comment]
Regarding our "offline" discussion, i will re-add headers for the files that originated from the orignal project.
As discussed it will be the license of this project (BSD-3), you will be mentioned first and i will add my partial copyright below.

**Comment by nick-zh** [comment]
Adjusted in the PR as per our discussion, please let me know if it is ok @arnaud-lb

**Comment by arnaud-lb** [comment]
No worries, I understand. Thank you for the PR, that's ok for me regarding the copyright notice.
